name: CI

on:
  push:
    branches: [ pixi-migration ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.39.4
        cache: true
    - run: pixi run lint
    - run: pixi run typecheck
    - run: pixi run test
