name: CI

on:
  push:
    branches: [ main ]
permissions: # so we can upload the docs
  contents: write
jobs:
  document:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.47.0
        cache: false
    - run: pixi run -e docs doc
    - name: deploy docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_build/html
        single-commit: true
    